import type { Metadata } from "next";
import "./globals.css";
import "phosphor-icons/src/css/icons.css";
import "../public/scss/default.scss";
import "../public/scss/section.scss";
import "../public/scss/halim.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
